DOMAIN = "ev_trip_tracker"

CONF_ODOMETER_SENSOR = "odometer_sensor"
CONF_BATTERY_SENSOR = "battery_sensor"
CONF_LOCATION_TRACKER = "location_tracker"
CONF_DRIVING_STATE_SENSOR = "driving_state_sensor"
CONF_BATTERY_CAPACITY = "battery_capacity"

ATTR_START_TIME = "start_time"
ATTR_END_TIME = "end_time"
ATTR_START_ODOMETER = "start_odometer"
ATTR_END_ODOMETER = "end_odometer"
ATTR_START_BATTERY = "start_battery"
ATTR_END_BATTERY = "end_battery"
ATTR_START_LOCATION = "start_location"
ATTR_END_LOCATION = "end_location"
ATTR_DISTANCE = "distance"
ATTR_ENERGY_USED = "energy_used"
ATTR_AVG_SPEED = "avg_speed"
ATTR_DURATION = "duration"
ATTR_START_ELEVATION = "start_elevation"
ATTR_END_ELEVATION = "end_elevation"
ATTR_ELEVATION_DIFF = "elevation_diff"
